name: PyPI Update

on:
  push:
    branches:
      - main

jobs:
  update_pypi:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install dependencies
        run: pip install --upgrade setuptools wheel twine

      - name: Build and publish to PyPI
        run: |
          python setup.py sdist bdist_wheel
          twine upload dist/*

